### ISSUE TITLE
[Catalog rules- Create new rule] Cần có option là none khi filter gift items 

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#24]
1. Go to admin > Marketing > Free gift pro > Catalog rule
2. Create new rule
3. Tại [Gift items], filter để search items
Actual result: Khi user filter by "type" nhưng muốn chuyển qua filter by "attribute set" thì phải reset filter
Expected result: Cần có option là "none" để khi user chuyển qua filter bởi trường khác thì không cần reset filter
http://prntscr.com/jsr8yq

**Comment by syluu** [comment]
Có option none rồi nhưng không hiện option none
![t i xu ng](https://user-images.githubusercontent.com/15073770/41187471-16b0b702-6bd4-11e8-9557-b20e06bac081.png)
Đang tìm nguyên nhân

**Comment by syluu** [comment]
Đã fix nhé
