### ISSUE TITLE
[Shopping cart] Cần restyle lại phần hiển thị free gifts

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#25]
1. Create new catalog rule 
2. Go to frontend, add item to cart
3. At mini cart, click "View and edit cart"
4. At Free gift, view từng items
http://prntscr.com/jsriub
Actual result: 1 phần thông tin của item không show hết 
Expected result: Cần có 1 scrollbar tại item nếu description của rule quá dài
http://prntscr.com/jsrk1e

**Comment by NguyenGiang93** [comment]
@syluu Bug này phần thông tin của free gift vẫn không show hết nếu description quá dài 
http://prntscr.com/jyexzm

**Comment by syluu** [comment]
@NguyenGiang93 ko viet description qua dai

**Comment by NguyenGiang93** [comment]
@syluu Thế thì chỗ này nên có dòng rõ ràng là được viết bn ký tự nhé. :)
