### ISSUE TITLE
[Create new catalog rules] Datatimepicker nên để là none nếu không set

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#28]
1. Go to admin > Marketing > Free gift pro > Catalog rules
2. Create new catalog rule
3. Tại date time không set data cho nó
4. Click button [Save]
Actual result: Hệ thống auto lấy ngày hiện tại
Expected result: Nên để là none nếu không set dữ liệu.
http://prntscr.com/jt5euz
----------------------------
Note: Hiện tại thời gian sử dụng đã hết nhưng rule vẫn có trạng thái là active
http://prntscr.com/jt5fbw
==> Hệ thống có thể xử lý theo cách nếu thời gian hết thì tự động chuyển status thành "Inactive"

**Comment by syluu** [comment]
Cái này kệ nó chứ :)
