### ISSUE TITLE
[Website- Catalog rule] Không cho phép hiển thị những rule đã được inactive trong backend

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#31]
1. Go to admin > Marketing > Free gift pro > Catalog rule
2. Click rule detail
3. [Active] = No
4. Click button [Save]
Actual result: Rule vẫn hiển thị trên website
Expected result: Không cho phép hiển thị nếu rule đó đã inactive
http://prntscr.com/jt7vdw

**Comment by tudn9x** [comment]
Tương tự lỗi #33
