### ISSUE TITLE
[Catalog rule] Rule đã inactive những vẫn hoạt động trên website

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#33]
1. Check rule: http://dreamcode.xyz/mage/leric/2110/admin/mw_freegift/promo_catalog/edit/id/3/#
=> Rule này đã inactive
2. Go to website > Add items to cart (http://dreamcode.xyz/mage/leric/2110/argus-all-weather-tank.html)
Actual result: 
1. Free gift thuộc rule đã inactive vẫn được add tới cart
2. Đã set buy 1 get 1 nhưng vẫn add tất cả free gifts tới cart
http://prntscr.com/jtaxgt

**Comment by tudn9x** [comment]
Catalog Rule sau khi save, phải chọn apply rule và chạy lại reindex mới có tác dụng.
