### ISSUE TITLE
[Config Show Free Gift on Category] Vẫn show free gift on catagory khi admin config =No

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#41]
1. Đi tới config của free gift
2. Chọn [Show Free Gift on Category]= No
3. Go to website để check
Actual result: Vẫn show free gift on catalog

**Comment by NguyenGiang93** [comment]
Phải flush cache mới update nhé :D 
Hiện ko thấy bug này
-leric-

**Comment by NguyenGiang93** [comment]
Đã làm như e nói nhé, nhưng chị thấy nó vẫn lỗi. :) Pls recheck

**Comment by syluu** [comment]
sorry chi, em nham voi chon "NO" o Enable Module:v
