### ISSUE TITLE
[Catalog rule] Xuất hiện error msg khi save catalog rule

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#48]
1. Go to admin > free gift pro > Catalog rule
2. Edit 1 vài thông tin và save
Actual result: Xuất hiện error msg
http://prntscr.com/jxcrld

**Comment by NguyenGiang93** [comment]
Cái này do cache thôi, giờ không bị nữa :+1:

**Comment by syluu** [comment]
Cái này do cache thôi, giờ không bị nữa +1
