### ISSUE TITLE
[Shopping cart rule] Nếu 2 shoping cart rule có free gift giống nhau thì nên tính gấp đôi QTy của free gift

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#49]
Check rule:
http://dreamcode.xyz/mage/leric/2110/admin/mw_freegift/promo_quote/edit/id/2/#
http://dreamcode.xyz/mage/leric/2110/admin/mw_freegift/promo_quote/edit/id/1/#
http://prntscr.com/jxd1u4

**Comment by syluu** [comment]
Hai gift cùng product nhưng khác rule nên tách ra làm 2 item (cái này để khách hàng biết gift này được nhận từ rule nào) 
http://prntscr.com/jxvuca
