### ISSUE TITLE
[Catalog rule] Vẫn add được 2 free gift tới cart mặc dù chỉ config là 1

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#52]
1. Tạo catalog rule: 
+ Không set condition cho nó
+ Set apply when buy X get Y: X=1, Y=1
http://prntscr.com/jyg2b2
2. Go to website > Add 1 sản phẩm tới cart 
Actual result: Vẫn add được 2 free gift tới cart
Expected result: Chỉ được add 1 free gift tới cart như config

**Comment by tudn9x** [comment]
kết quả buy x get y ở đây là giá trị qty của sản phẩm gift trong giỏ hàng, nghĩa là sản phẩm gift có qty bằng 1. 

Khác với số lượng sản phẩm gift e ạ. Ví dụ trong backend họ chọn có bn sản phẩm gift thì tất cả gift vẫn sẽ được add to cart. Còn giá trị qty mới theo quy định buy x get y
