### ISSUE TITLE
[Shopping cart] màn hình loading trong thời gian dài khi add config product to cart

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#57]
1. Create new catalog rule. Trong đó free gift là sản phẩm config
Note: Nếu 1 sản phẩm con là sắp hết hàng.
Ex: + Config Buy 1 get 1
     + Sản phẩm con: Qty =2
2. Add 3 items to cart
http://prntscr.com/k1owd3
3. Add config to cart: Chọn option to add product to cart
http://prntscr.com/k1ox9z
4. Click button [Add to cart]
Actual result: Màn hình loading trong thời gian dài
http://prntscr.com/k1ozjp
--------------
Tương tự như trên nhưng đối với sản phẩm simple:  Sản phẩm free gift là simple nhưng ko đủ items để add to cart
=> Mini bị thay đổi style và không thêt checkout this order.
http://prntscr.com/k1p7sn

**Comment by syluu** [comment]
đã fix nhé

**Comment by NguyenGiang93** [comment]
https://www.youtube.com/watch?v=VjtmPHDLoOs&feature=youtu.be
Leric, check video để rõ bug này nhé.
Nếu bây giờ add items to cart =9 -> Sau đó thay đổi qty =11. Tức là 1 sản phẩm free gift sẽ không đủ. 
==> At mini cart, không show button checkout.

**Comment by syluu** [comment]
Vì không đủ sản phẩm gift để add nên không cho checkout nhé.
Đã sửa thành add gift với ố lượng lơn nhất có thể, để không bị thông báo và không hiện button checkout như trên.
