### ISSUE TITLE
Items trong cart đang bị sai

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#58]
1. Check catalog rule: http://dreamcode.xyz/mage/leric/2110/admin/mw_freegift/promo_catalog/edit/id/16/ (Free gift bao gồm sản phẩm simple và config)
2. Add 1 sản phẩm thỏa mãn đk của rule 1 tới cart (Lúc này sản phẩm free gift là config sẽ chưa đc add to cart)
3. Add 1 sản phẩm mà sản phẩm này cũng nằm trong free gift ->http://prntscr.com/k20dne
http://dreamcode.xyz/mage/leric/2110/erika-running-short.html
4. Go to cart, add sản phẩm free gift (sản phẩm config tới cart) 
http://prntscr.com/k20egi
Note: Giống với sản phẩm vừa được add trước đó
Actual result:  sản phẩm free gift được add sẽ cộng dồn với sản phẩm add trước đó. Và nó tính price như sản phẩm thông thường
http://prntscr.com/k20fkt
==> Check video: https://www.youtube.com/watch?v=1ueB4_zcwvg&feature=youtu.be

**Comment by syluu** [comment]
Đã Fix nhé!
