### ISSUE TITLE
[Mini cart] Total Qty không được update tại mini cart

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#63]
1. Add 1 sp to cart (Đồng thời sản phẩm free gift- sản phẩm simple cũng được add to cart)
http://prntscr.com/k3w7pj
2. Đi tới trang shopping cart, add tiếp sản phẩm free gift - sản phẩm config
Actual result: Total Qty và items trong mini cart vẫn không được update
http://prntscr.com/k3w9wx
Note: Đã refesh nhiều lần nhưng vẫn không thấy hiện ra

**Comment by syluu** [comment]
qty trên minicart update muộn
