### ISSUE TITLE
Cần confirm khi change qty của sản phẩm thỏa mãn điều kiện free gift

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#65]
Hôm trước test thì mỗi lần thay đổi qty của sản phẩm thỏa mãn rule thì tất cả sản phẩm free gift (simple và config) đều tự động update. Những giờ test thì sản phẩm free gift- config sẽ bị xóa đi bắt user add lại.
==> Cái nào mới là đúng?

**Comment by syluu** [comment]
Đấy là bug nhé, bây giờ em đã fix bug này rồi

**Comment by NguyenGiang93** [comment]
Done
