### ISSUE TITLE
Cần confirm

### ISSUE THREAD

**Issue by NguyenGiang93** [htmyheart/magento-dev#67]
1. Catalog rule: nhận free gift nếu sản phẩm thuộc catagory A
2. Shopping cart rule: nếu trong cart có qty =2
==> Nếu sản phẩm trong cart thỏa mãn cả 2 đk trên thì cả 2 rule này đều đc apply đúng ko?
Giả sử trường hợp: Add 1 sản phẩm thỏa mãn catalog rule => Sản phẩm free gift sẽ được add to cart (Qty=2) => Thỏa mãn điều kiện của shopping cart rule
Vậy trường hợp rule sẽ apply ntn?

**Comment by syluu** [comment]
@NguyenGiang93 
Cả 2 rule đều được apply nhé
